# Generated by Django 2.1 on 2019-06-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0012_auto_20190620_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='runs',
            name='bal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bal', to='iplclone.Ball'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runs',
            name='ball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball', to='iplclone.Ball'),
        ),
    ]
