# Generated by Django 2.1 on 2019-06-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0014_auto_20190620_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='bal',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bal', to='iplclone.Ball'),
        ),
    ]
