# Generated by Django 2.2.1 on 2019-06-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='winner',
        ),
    ]
