# Generated by Django 2.2.1 on 2019-06-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0002_remove_season_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ining',
            name='batting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplclone.Team'),
        ),
    ]
