# Generated by Django 2.2.1 on 2019-06-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0003_auto_20190617_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ining',
            old_name='ining_number',
            new_name='ining',
        ),
    ]
