# Generated by Django 2.2.1 on 2019-06-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0004_auto_20190617_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ining',
            old_name='ining',
            new_name='inings',
        ),
    ]
