# Generated by Django 2.2.1 on 2019-06-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0005_auto_20190617_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ining',
            name='bowling_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bowling_team', to='iplclone.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ining',
            name='batting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_team', to='iplclone.Team'),
        ),
    ]
