# Generated by Django 2.2.1 on 2019-06-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0006_auto_20190617_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ining',
            name='bowling_team',
        ),
    ]
