# Generated by Django 2.1 on 2019-06-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0007_remove_ining_bowling_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ining',
            name='inings',
            field=models.IntegerField(),
        ),
    ]
