# Generated by Django 2.1 on 2019-06-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0008_auto_20190620_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tmp_match_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
