# Generated by Django 2.1 on 2019-06-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0009_match_tmp_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='umpire1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umpire1', to='iplclone.Umpire'),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umpire2', to='iplclone.Umpire'),
        ),
    ]
