# Generated by Django 2.1 on 2019-06-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0013_auto_20190620_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runs',
            name='ball',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ball', to='iplclone.Ball'),
        ),
    ]
