# Generated by Django 2.1 on 2019-06-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplclone', '0015_result_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
